# Application configuration
application-name: gen_ai_training

spring:
  main:
    eb-application-type: none

client:
  azureopenai:
    key: ${DIAL_API_KEY}
    endpoint: ${DIAL_API_ENDPOINT}
    deployment-name: gpt-4o